export const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

export const PITCH_DETECTION = {
  MIN_FREQUENCY: 50,
  MAX_FREQUENCY: 2000,
  MIN_CLARITY: 0.6,
  CLARITY_THRESHOLD: 0.8,
  MIN_VOLUME_DECIBELS: -40,
  FFT_SIZE: 4096,
  SMOOTHING_TIME_CONSTANT: 0.8,
  SAMPLE_RATE: 44100,
  SILENCE_CLARITY: 0.4,
  SILENCE_FRAMES_TO_REARM: 6
}

export const DETECTION_TIMING = {
  COOLDOWN_MS: 120,
  CONFIDENCE_THRESHOLD: 1,
  HISTORY_WINDOW_MS: 700,
  REFRACTORY_MS: 700,
  SUCCESS_DELAY_MS: 600,
  SUCCESS_RESET_MS: 1500,
  DETECTION_RESET_MS: 800
}

export const COLORS = {
  PRIMARY: '#667eea',
  SECONDARY: '#764ba2',
  SUCCESS: '#4CAF50',
  ERROR: '#f44336',
  WARNING: '#ff9800',
  INFO: '#2196F3'
}

export const ANIMATION_DURATIONS = {
  CARD_SWIPE: 300,
  FLIP: 300,
  FADE: 300
}

export const BREAKPOINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1024
}

